/** Generated by scripts/sync-versions.mjs. Do not edit by hand. */
export const DEVKIT_PACKAGE_VERSION = "0.5.1";
export const DEFAULT_DEVKIT_VERSION_RANGE = "^0.5.1";
export const DEFAULT_DEVTOOLS_VERSION_RANGE = "^0.1.1";

export const EXTERNAL_PRODUCT_VERSION_RANGES = {
  agentKit: "^0.2.4",
  swiperAdapter: "^0.2.0",
  spacesDeployer: "^0.2.0",
} as const;
