/** Generated by scripts/sync-versions.mjs. Do not edit by hand. */
export const DEVKIT_PACKAGE_VERSION = "0.1.0";
export const DEFAULT_DEVKIT_VERSION_RANGE = "^0.1.0";

export const EXTERNAL_PRODUCT_VERSION_RANGES = {
  agentKit: "^0.1.0",
  swiperAdapter: "^0.1.0",
  spacesDeployer: "^0.1.0",
} as const;
