import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import semver from "semver";

const workspaceRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export const DEVKIT_PACKAGES = [
  "@slicemedia/devkit",
  "@slicemedia/devkit-core",
  "@slicemedia/devkit-addon",
  "@slicemedia/devkit-cli",
  "@slicemedia/create-devkit",
];

const packageDirectories = new Map([
  ["@slicemedia/devkit", "packages/devkit"],
  ["@slicemedia/devkit-core", "packages/core"],
  ["@slicemedia/devkit-addon", "packages/addon"],
  ["@slicemedia/devkit-cli", "packages/cli"],
  ["@slicemedia/create-devkit", "packages/create-devkit"],
]);

const externalProductDefinitions = {
  agentKit: "@slicemedia/agent-kit",
  swiperAdapter: "@slicemedia/swiper-adapter",
  spacesDeployer: "@slicemedia/spaces-deployer",
};

function workspacePath(relativePath) {
  return resolve(workspaceRoot, relativePath);
}

async function readJson(relativePath) {
  return JSON.parse(await readFile(workspacePath(relativePath), "utf8"));
}

function assertSemver(value, label) {
  if (typeof value !== "string" || semver.valid(value) !== value) {
    throw new Error(
      `${label} must be an exact semantic version; received ${JSON.stringify(value)}.`,
    );
  }
}

function assertCaretRange(value, label) {
  if (typeof value !== "string" || !value.startsWith("^")) {
    throw new Error(`${label} must be an explicit caret range.`);
  }
  assertSemver(value.slice(1), label);
  if (semver.validRange(value) === null) throw new Error(`${label} is not a valid semver range.`);
}

async function readDevKitPackages() {
  const packages = [];
  for (const name of DEVKIT_PACKAGES) {
    const directory = packageDirectories.get(name);
    const manifest = await readJson(`${directory}/package.json`);
    if (manifest.name !== name) {
      throw new Error(`${directory}/package.json must be named ${name}.`);
    }
    assertSemver(manifest.version, `${name} version`);
    packages.push({ directory, manifest, name, version: manifest.version });
  }
  return packages;
}

async function readExternalProducts() {
  const configuration = await readJson("config/external-products.json");
  if (configuration.schemaVersion !== 1 || typeof configuration.products !== "object") {
    throw new Error("config/external-products.json must use schema version 1.");
  }

  const configuredKeys = Object.keys(configuration.products).sort();
  const expectedKeys = Object.keys(externalProductDefinitions).sort();
  if (JSON.stringify(configuredKeys) !== JSON.stringify(expectedKeys)) {
    throw new Error(`External product keys must be exactly: ${expectedKeys.join(", ")}.`);
  }

  const products = {};
  for (const [key, packageName] of Object.entries(externalProductDefinitions)) {
    const configured = configuration.products[key];
    if (configured?.packageName !== packageName) {
      throw new Error(`External product ${key} must reference ${packageName}.`);
    }
    assertCaretRange(configured.range, `${packageName} compatibility range`);
    products[key] = { packageName, range: configured.range };
  }
  return products;
}

function renderCoreVersion(version) {
  return `/** Generated by scripts/sync-versions.mjs from packages/core/package.json. */\nexport const CORE_VERSION = ${JSON.stringify(version)};\n`;
}

function renderCreatorVersions(version, externalProducts, devtoolsRange) {
  return `/** Generated by scripts/sync-versions.mjs. Do not edit by hand. */
export const DEVKIT_PACKAGE_VERSION = ${JSON.stringify(version)};
export const DEFAULT_DEVKIT_VERSION_RANGE = ${JSON.stringify(`^${version}`)};
export const DEFAULT_DEVTOOLS_VERSION_RANGE = ${JSON.stringify(devtoolsRange)};

export const EXTERNAL_PRODUCT_VERSION_RANGES = {
  agentKit: ${JSON.stringify(externalProducts.agentKit.range)},
  swiperAdapter: ${JSON.stringify(externalProducts.swiperAdapter.range)},
  spacesDeployer: ${JSON.stringify(externalProducts.spacesDeployer.range)},
} as const;
`;
}

export async function expectedVersionFiles() {
  const packages = await readDevKitPackages();
  const versions = [...new Set(packages.map(({ version }) => version))];
  if (versions.length !== 1) {
    throw new Error(
      `Fixed DevKit packages must share one version; found ${packages
        .map(({ name, version }) => `${name}@${version}`)
        .join(", ")}.`,
    );
  }
  const version = versions[0];
  const externalProducts = await readExternalProducts();
  const devtools = await readJson("packages/devtools/package.json");
  const devtoolsCompatibility = await readJson("config/devtools-compatibility.json");
  assertSemver(devtools.version, "DevTools version");
  assertCaretRange(devtoolsCompatibility.range, "DevTools compatibility range");
  if (
    devtools.name !== "@slicemedia/devtools" ||
    devtoolsCompatibility.schemaVersion !== 1 ||
    devtoolsCompatibility.packageName !== devtools.name ||
    !semver.satisfies(devtools.version, devtoolsCompatibility.range, { includePrerelease: true })
  ) {
    throw new Error("DevTools must match its independent creator compatibility range.");
  }
  return {
    externalProducts,
    packages,
    version,
    files: new Map([
      ["packages/core/src/version.ts", renderCoreVersion(version)],
      [
        "packages/create-devkit/src/versions.generated.ts",
        renderCreatorVersions(version, externalProducts, devtoolsCompatibility.range),
      ],
    ]),
  };
}

export async function syncVersionFiles() {
  const state = await expectedVersionFiles();
  const written = [];
  for (const [relativePath, expected] of state.files) {
    const path = workspacePath(relativePath);
    const current = await readFile(path, "utf8").catch(() => undefined);
    if (current === expected) continue;
    await writeFile(path, expected);
    written.push(relativePath);
  }
  return { ...state, written };
}

export async function checkVersionConsistency() {
  const state = await expectedVersionFiles();
  const errors = [];

  for (const [relativePath, expected] of state.files) {
    const current = await readFile(workspacePath(relativePath), "utf8").catch(() => undefined);
    if (current !== expected) {
      errors.push(`${relativePath} is stale; run pnpm version:sync.`);
    }
  }

  const changesets = await readJson(".changeset/config.json");
  const fixedGroups = Array.isArray(changesets.fixed) ? changesets.fixed : [];
  const hasExactFixedGroup = fixedGroups.some(
    (group) =>
      Array.isArray(group) &&
      JSON.stringify([...group].sort()) === JSON.stringify([...DEVKIT_PACKAGES].sort()),
  );
  if (!hasExactFixedGroup) {
    errors.push("Changesets must keep the five DevKit packages in one fixed version group.");
  }
  if (
    [...fixedGroups, ...(changesets.linked ?? [])].some((group) =>
      group.includes("@slicemedia/devtools"),
    ) ||
    changesets.ignore?.includes("@slicemedia/devtools")
  ) {
    errors.push("DevTools must remain independently versioned and releasable through Changesets.");
  }
  if (!Array.isArray(changesets.ignore) || !changesets.ignore.includes("webflow-project")) {
    errors.push("Changesets must ignore the private starter fixture package.");
  }

  if (errors.length > 0) throw new Error(errors.join("\n"));
  return state;
}
