export {
  AddonDefinitionError,
  AddonLifecycleError,
  createAddon,
  defineAddon,
  getAddonMetadata,
  initializeAddon,
} from "@slicemedia/devkit-core";

export type {
  AddonCondition,
  AddonValueConstraints,
  AddonInspectionContext,
  AddonDiagnostics,
  AddonDiagnostic,
  AddonDependencyDiagnostic,
  AddonAttribute,
  AddonStructureAttribute,
  AddonStructureNode,
  AddonDefinition,
  AddonDefinitionInput,
  AddonDependency,
  AddonDependencyKind,
  AddonEnvironment,
  AddonEnvironmentInput,
  AddonErrorEvent,
  AddonInstance,
  AddonInstanceEventMap,
  AddonLifecycleHooks,
  AddonLifecycleEvent,
  AddonLifecycleMethod,
  AddonMetadata,
  AddonOptionMetadata,
  AddonOptionsChange,
  AddonPlacement,
  AddonSetupContext,
  AddonStatus,
  AddonStatusChange,
  AddonUsage,
  AddonValueType,
  Cleanup,
  DataWftAttribute,
  MaybePromise,
} from "@slicemedia/devkit-core";
